#since organization changed
name: DigitalOcean App Platform deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v2.0.6
